
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class IngresarProductos extends javax.swing.JPanel {
    //Vector de la tabla
    public static List<Productos> productos = new ArrayList<>();
    
    
    
    
    
    //Variable que me almacena el id del producto en un contadorID "Variable Global"
    private static int contadorID = 1;
    
    // linea para acceder al modelo de la tabla (Mantener los datos cargados de la tabla
    DefaultTableModel mt = Datoscargados.mt;
    
    
    
    /**
     * Creates new form pagina1
     */
    public IngresarProductos() {
        initComponents();
        
        //esto es para definir la forma de como se va a mostrar la tabla 
        String[] id = {"ID","Nombre","Valor Compra","Cantidad (Stock)","Valor Venta"};
        
        //Ingresar el id en la tabla ()
        mt.setColumnIdentifiers(id);
        
        //Linea para inicializar la tabla y sus datos
        jTable1.setModel(mt);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        etvalor = new javax.swing.JTextField();
        etnombre = new javax.swing.JTextField();
        etcantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnanadir = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        p1.setBackground(new java.awt.Color(245, 245, 245));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        etcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etcantidadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre del Producto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Valor de Compra ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad del producto");

        btnanadir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnanadir.setText("Añadir");
        btnanadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanadirActionPerformed(evt);
            }
        });

        btnborrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Inventario de productos ");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnanadir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(etcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnanadir)
                    .addComponent(btnactualizar)
                    .addComponent(btnborrar))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    // Metodo para ingresar productos a la tabla
    private void btnanadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanadirActionPerformed

    try{
        
    int id = contadorID;
    contadorID++; // Incrementa para el siguiente producto (ID)

    //Obtener los valores del textfield (Valores de la tabla)
    String pNombre = etnombre.getText();
    double valor = Double.valueOf(etvalor.getText());
    int pCantidad = Integer.valueOf(etcantidad.getText());

    // Cálculo de la ganancia (Se saca el 10% a cada producto, luego lo sumamos y a ese valor lo vendemos)
    double ganancia = valor * 0.05;
    double total_ganancia = ganancia + valor; 

    // Agregar fila a la tabla
    mt.addRow(new Object[] {id, pNombre, valor, pCantidad, total_ganancia});

    // Limpiar campos
    etnombre.setText("");
    etvalor.setText("");
    etcantidad.setText("");
    
    //Añadir al vector
    Productos nuevoProducto = new Productos(id,pNombre,valor,pCantidad,total_ganancia);
    productos.add(nuevoProducto);
    
    //Ingresar un producto al arreglo global que esta en el principal
    Principal.productos.add(new Productos(id, pNombre, valor, pCantidad, total_ganancia));
     
    //Ingresar un producto al arreglo global que esta en BuscarProductos
    BuscarProductos.productos.add(new Productos(id, pNombre, valor, pCantidad, total_ganancia));
    
    //Mostrar el vector
    for(Productos p : productos){
        System.out.println("id:"+p.getId());
        System.out.println("Nombre:"+p.getNombre());
        System.out.println("Valor Compra"+p.getValorCompra());
        System.out.println("Cantidad:"+p.getCantidad());
        System.out.println("La ganancia es:"+p.getGanancia());
        System.out.println("-------------------------------");
    }
    
    }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingrese un dato valido por favor");
        }
    }//GEN-LAST:event_btnanadirActionPerformed

    //Borra un dato de la tabla
    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        mt.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_btnborrarActionPerformed

    //Actualizar un campo de la tabla
    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        //Selecciona fila 
        int selectedRow = jTable1.getSelectedRow();

        // Actualizar el nombre solo si no está vacío
        String nombre = etnombre.getText();
        if (!nombre.isEmpty()) {
        mt.setValueAt(nombre, selectedRow, 1);
        }

        // Actualizar el valor solo si no está vacío
        String valorText = etvalor.getText();
        if (!valorText.isEmpty()) {
        double valor = Double.parseDouble(valorText);
        mt.setValueAt(valorText, selectedRow, 2);

        // Cálculo de ganancia (precio + 5%)
        double ganancia = valor + (valor * 0.05);
        mt.setValueAt(ganancia, selectedRow, 4);
        }

        // Actualizar la cantidad solo si no está vacía
        String cantidad = etcantidad.getText();
        if (!cantidad.isEmpty()) {
        mt.setValueAt(cantidad, selectedRow, 3);
      }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void etcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etcantidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnanadir;
    private javax.swing.JButton btnborrar;
    private javax.swing.JTextField etcantidad;
    private javax.swing.JTextField etnombre;
    private javax.swing.JTextField etvalor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel p1;
    // End of variables declaration//GEN-END:variables
}
